// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6j_qvaJixxHw-hzdnqRr0JxIRuW2xVdg',
    appId: '1:87617393730:web:d6ee8f1627947fa73849db',
    messagingSenderId: '87617393730',
    projectId: 'campussync-a8ebc',
    authDomain: 'campussync-a8ebc.firebaseapp.com',
    storageBucket: 'campussync-a8ebc.firebasestorage.app',
    measurementId: 'G-SEV6S382HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu58Wf1ZceOazSVp92T2rzokvQIO_Hagw',
    appId: '1:87617393730:android:16b39ad5d78a0a603849db',
    messagingSenderId: '87617393730',
    projectId: 'campussync-a8ebc',
    storageBucket: 'campussync-a8ebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWXrl_01-iTnZLJeHRQUjxkXdtCwouuN0',
    appId: '1:87617393730:ios:05987bd14f0b9c023849db',
    messagingSenderId: '87617393730',
    projectId: 'campussync-a8ebc',
    storageBucket: 'campussync-a8ebc.firebasestorage.app',
    iosBundleId: 'com.example.campusSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWXrl_01-iTnZLJeHRQUjxkXdtCwouuN0',
    appId: '1:87617393730:ios:05987bd14f0b9c023849db',
    messagingSenderId: '87617393730',
    projectId: 'campussync-a8ebc',
    storageBucket: 'campussync-a8ebc.firebasestorage.app',
    iosBundleId: 'com.example.campusSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6j_qvaJixxHw-hzdnqRr0JxIRuW2xVdg',
    appId: '1:87617393730:web:8cfa7b2ff5779be23849db',
    messagingSenderId: '87617393730',
    projectId: 'campussync-a8ebc',
    authDomain: 'campussync-a8ebc.firebaseapp.com',
    storageBucket: 'campussync-a8ebc.firebasestorage.app',
    measurementId: 'G-9WNP8PPY4M',
  );
}
